import { beforeEach, describe, expect, it, vi } from "vitest";

const { createMock } = vi.hoisted(() => ({
  createMock: vi.fn(),
}));

vi.mock("../config/env", () => ({
  env: {
    geminiApiKey: "test-api-key",
    port: 3001,
  },
}));

vi.mock("@google/genai", () => {
  class GoogleGenAI {
    interactions = {
      create: createMock,
    };
  }

  return {
    GoogleGenAI,
  };
});

import { askGemini } from "../services/geminiService";

describe("geminiService", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns the response generated by Gemini", async () => {
    createMock.mockResolvedValue({
      output_text: "This is a Gemini response",
    });

    const response = await askGemini("Hello Gemini");

    expect(response).toBe("This is a Gemini response");

    expect(createMock).toHaveBeenCalledWith({
      model: "gemini-3.8-flash",
      input: "Hello Gemini",
    });
  });
});