import { beforeEach, describe, expect, it, vi } from "vitest";

const createMock = vi.fn();

vi.mock("google-generativeai", () => ({
    GoogleGenAI: vi.fn().mockImplementation(() => ({
        interactions: {
            create: createMock,
        },
    })),
}));

import { askGemini } from "../services/geminiService";

describe("geminiService", () => {
    beforeEach(() => {
        vi.clearAllMocks();
    });

    it("returns the response generated by Gemini", async () => {
       createMock.mockResolvedValue({
            output_text: "This is a Gemini response",
       });

       const response = await askGemini("Hello Gemini");

       expect(response).toBe("This is a Gemini response");

       expect(createMock).toHaveBeenCalledWith({
            model: "gemini-3.8-flash",
            input: "Hello Gemini",
       });
    });
});